#!/usr/bin/env bash
set -euo pipefail
# modules/apps/wazuh/configs/wazuh_indexer/render-security-config.sh — #855
#
# Runs ONCE per `docker compose up` inside the pinned wazuh-indexer image, as
# the wazuh-securityconfig-init one-shot, BEFORE the indexer starts.
#
# It exists because the credentials that actually gate the Wazuh event store
# live in a bcrypt file, not in an env var, and the image ships that file
# pre-populated with Wazuh's PUBLISHED demo hashes. Everything written here is
# derived from .env secrets; nothing is committed.
#
# Writes:
#   /usr/share/wazuh-indexer/config/opensearch-security/internal_users.yml
#   /usr/share/wazuh-indexer/config/opensearch-security/config.yml
#   /usr/share/wazuh-indexer/config/opensearch-security/roles_mapping.yml
#   /wazuh-config-mount/etc/ossec.conf      (copy of the tracked file)
#   /wazuh-config-mount/etc/authd.pass      (agent-enrollment shared secret)
#
# Idempotent: it rewrites the same content from the same inputs every run.

SEC_DIR=/usr/share/wazuh-indexer/config/opensearch-security
MGR_DIR=/wazuh-config-mount/etc
HASH_TOOL=/usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh
export JAVA_HOME=/usr/share/wazuh-indexer/jdk

# SECRET GATE (#855 rev-B, review blocker 1). These four `:?` lines — plus the
# two in render-dashboard-config.sh — are now the ONLY fail-closed check on the
# module's secrets: the parse-time `${VAR:?}` guards were removed from
# modules/apps/wazuh/compose.yml because the top-level `include:` is
# unconditional and Compose resolves `:?` before profile filtering, so a `:?`
# there bricked `docker compose` box-wide on every non-wazuh box. Failing here
# is strictly better: it is loud, it is in the module that owns the secret, and
# every long-running wazuh service gates on this one-shot completing
# successfully — so an empty secret still stops the module dead instead of
# letting Wazuh's PUBLISHED demo credentials survive on a real box.
: "${WAZUH_INDEXER_PASSWORD:?WAZUH_INDEXER_PASSWORD is empty - run rzfz init or rzfz upgrade}"
: "${WAZUH_DASHBOARD_PASSWORD:?WAZUH_DASHBOARD_PASSWORD is empty - run rzfz init or rzfz upgrade}"
: "${WAZUH_AUTHD_PASSWORD:?WAZUH_AUTHD_PASSWORD is empty - run rzfz init or rzfz upgrade}"
# Nothing below reads it: it is gated HERE because the manager and the dashboard
# hand it straight to an upstream entrypoint that would happily configure the
# wazuh-wui API account with an empty password.
: "${WAZUH_API_PASSWORD:?WAZUH_API_PASSWORD is empty - run rzfz init or rzfz upgrade}"
: "${WAZUH_AUTH_MODE:?WAZUH_AUTH_MODE is empty - expected native_oidc or forward_auth}"

bcrypt() {
    # hash.sh prints a banner on some builds; the hash is the last line.
    bash "$HASH_TOOL" -p "$1" | tail -n 1 | tr -d '\r\n'
}

ADMIN_HASH="$(bcrypt "$WAZUH_INDEXER_PASSWORD")"
DASH_HASH="$(bcrypt "$WAZUH_DASHBOARD_PASSWORD")"
[ -n "$ADMIN_HASH" ] && [ -n "$DASH_HASH" ] || {
    echo "ERROR(#855): $HASH_TOOL produced no hash - refusing to leave the" >&2
    echo "  image's published demo hashes in place." >&2
    exit 1
}

mkdir -p "$SEC_DIR" "$MGR_DIR"

# ── internal_users.yml ────────────────────────────────────────────────────
# ONLY the two accounts this stack uses. The four demo accounts the image
# ships are DELETED, not re-hashed: an account nothing uses is an attack
# surface nothing watches.
cat > "$SEC_DIR/internal_users.yml" <<EOF
---
# GENERATED by render-security-config.sh (#855) from .env secrets.
# Do not edit: the wazuh-securityconfig-init one-shot overwrites it on every
# \`docker compose up\`, and wazuh-securityadmin then applies it to the
# security index (DECISION-12).
_meta:
  type: "internalusers"
  config_version: 2

admin:
  hash: "${ADMIN_HASH}"
  reserved: true
  backend_roles:
    - "admin"
  description: "razzfazz.ai generated indexer admin (WAZUH_INDEXER_PASSWORD)"

kibanaserver:
  hash: "${DASH_HASH}"
  reserved: true
  description: "razzfazz.ai generated dashboard service account (WAZUH_DASHBOARD_PASSWORD)"
EOF

# ── config.yml — the authc chain ──────────────────────────────────────────
# basic_internal_auth_domain stays FIRST (order 0, challenge false) so the
# dashboard's own kibanaserver service account and securityadmin keep working;
# the OIDC domain is order 1 and is what real users authenticate through.
if [ "$WAZUH_AUTH_MODE" = "native_oidc" ]; then
    # WAZUH_OIDC_CLIENT_ID is deliberately NOT required here any more: the
    # discovery URL below names the application slug, and the indexer's authc
    # chain never sees the client id (only the dashboard sends it).
    : "${AUTHENTIK_DOMAIN:?AUTHENTIK_DOMAIN is empty}"
    # UNQUOTED heredoc — ${AUTHENTIK_DOMAIN} must expand. The price is that a
    # backtick inside it is COMMAND SUBSTITUTION, prose or not, so every
    # backtick in this block stays backslash-escaped (rev-C 2). Guarded by
    # tests/unit/consistency/test_855_wazuh_render_heredocs.py.
    cat > "$SEC_DIR/config.yml" <<EOF
---
# GENERATED by render-security-config.sh (#855).
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
    authc:
      basic_internal_auth_domain:
        description: "Local service accounts (kibanaserver, admin)"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: "basic"
          challenge: false
        authentication_backend:
          type: "intern"
      openid_auth_domain:
        description: "Authentik SSO (blueprint 37-wazuh.yaml)"
        http_enabled: true
        transport_enabled: false
        order: 1
        http_authenticator:
          type: "openid"
          challenge: false
          config:
            subject_key: preferred_username
            roles_key: groups
            # APPLICATION SLUG, not the client_id (rev-B LOW 18). Blocker 4
            # split the Authentik app in two: the proxy app \`wazuh\` carries the
            # forward-auth gate, the hidden \`wazuh-oidc\` app carries this OAuth2
            # provider — and /application/o/<slug>/ resolves by the slug of the
            # app that OWNS the provider. Mirrors modules/gitea/init-gitea.sh.
            openid_connect_url: "https://${AUTHENTIK_DOMAIN}/application/o/wazuh-oidc/.well-known/openid-configuration"
            openid_connect_idp:
              enable_ssl: true
              # The CA superset scripts/lib.sh::ensure_oidc_ca_superset (#152)
              # maintains: system roots + the Caddy internal CA on a
              # TLS_MODE=internal box. Bind-mounted read-only into the
              # indexer by modules/apps/wazuh/compose.yml, so it is read
              # LIVE rather than copied — a copy made by THIS one-shot
              # would land in the one-shot's own layer and be discarded
              # when it exits (the certs volume is :ro for consumers and
              # 0500 root-owned by the generator).
              #
              # #1625: this path lives under OPENSEARCH_PATH_CONF
              # (/usr/share/wazuh-indexer/config) so the JVM SecurityManager
              # grants the opensearch-security plugin FilePermission "read" on
              # it. A path outside the config tree (the old
              # /usr/local/share/ca-certificates/...) is denied at authenticator
              # init — see the indexer CA mount note in
              # modules/apps/wazuh/compose.yml.
              pemtrustedcas_filepath: /usr/share/wazuh-indexer/config/caddy-ca.pem
        authentication_backend:
          type: noop
EOF
else
    cat > "$SEC_DIR/config.yml" <<'EOF'
---
# GENERATED by render-security-config.sh (#855) — WAZUH_AUTH_MODE=forward_auth,
# so no OIDC domain is configured; Caddy's Authentik forward_auth is the only
# gate and users share the local `admin` account inside the dashboard.
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
    authc:
      basic_internal_auth_domain:
        description: "Local accounts only"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: "basic"
          challenge: true
        authentication_backend:
          type: "intern"
EOF
fi

# ── roles_mapping.yml — Authentik group -> OpenSearch backend role ────────
# The `groups` claim carries Authentik group NAMES (the blueprint attaches
# "razzfazz.ai OAuth Mapping: groups"), and config.yml sets roles_key: groups.
cat > "$SEC_DIR/roles_mapping.yml" <<'EOF'
---
# GENERATED by render-security-config.sh (#855).
_meta:
  type: "rolesmapping"
  config_version: 2

all_access:
  reserved: false
  backend_roles:
    - "admin"
    - "razzfazz.ai Super Admins"
  description: "Full cluster admin: the local admin account + Authentik Super Admins"

kibana_user:
  reserved: false
  backend_roles:
    - "razzfazz.ai Wazuh Users"
  description: "Dashboard access for the module's Authentik group"

readall:
  reserved: false
  backend_roles:
    - "razzfazz.ai Wazuh Users"
  description: "Read access to Wazuh indices for the module's Authentik group"

# #1537: the ROLE is `kibana_server`; `kibanaserver` is the USER. Mapping the
# user onto a role of its own name maps it onto NOTHING — the security API
# answers `role 'kibanaserver' not found`, the account authenticates with zero
# permissions, and the dashboard loops on
#   [security_exception]: no permissions for [cluster:monitor/nodes/info]
#   and User [name=kibanaserver, backend_roles=[]]
# while the browser shows "Wazuh dashboard server is not ready yet" forever.
# `kibana_server` is the reserved STATIC role that carries exactly what the
# dashboard needs: cluster_monitor, cluster_composite_ops,
# manage_point_in_time, the index-template admin actions and the .kibana /
# .opensearch_dashboards index permissions. Measured on 0.91 2026-09-05:
#   GET _plugins/_security/api/roles/kibana_server  → reserved, cluster_monitor …
#   GET _plugins/_security/api/roles/kibanaserver   → NOT_FOUND
kibana_server:
  reserved: true
  users:
    - "kibanaserver"
EOF

# ── manager config drop ───────────────────────────────────────────────────
# /wazuh-config-mount is what the manager's entrypoint installs into
# /var/ossec. ossec.conf is the tracked file, copied verbatim; authd.pass is
# the generated enrollment secret and must never be a tracked file.
cp /src/ossec.conf "$MGR_DIR/ossec.conf"

# ── <allowed-ips> widening (DECISION-4) ───────────────────────────────────
# TWO variables since rev-B (review LOW 15), not one:
#
#   WAZUH_ALLOWED_IPS         widens the 1514 agent event channel (TLS +
#                             per-agent key). #1537: it does NOT widen 1515.
#                             wazuh-authd refuses an <allowed-ips> element
#                             inside <auth> (XML_INVELEM 1230) and the manager
#                             then does not start at all, so the enrolment port
#                             is fenced by WAZUH_MANAGER_HOST_BIND and the
#                             authd password — not by this variable.
#   WAZUH_SYSLOG_ALLOWED_IPS  widens the UNAUTHENTICATED 514 syslog listener.
#
# Pre-rev-B one variable was applied with `sed …/g`, so an operator widening
# the agent ports for a fleet ALSO silently opened the one listener that has no
# authenticator at all — anything inside the new range could inject forged
# events. Separating them makes that an explicit second decision.
#
# Empty (the default for both) leaves the tracked loopback + docker-bridge
# entries exactly as they are. The `cp` above runs first on every invocation,
# so this stays idempotent by construction.
#
# Every value is SHAPE-VALIDATED before it reaches awk. Pre-rev-B the raw
# string was interpolated straight into a `sed` replacement, where a
# metacharacter either broke the expression (fail-closed via set -e, usually)
# or quietly altered it.
_reject_cidr() {
    echo "ERROR(#855): $1 rejected the value below - $3" >&2
    echo "  value: $2" >&2
    exit 1
}

_build_allowed_ips() {
    # $1 = variable name (diagnostics only), $2 = comma-separated list.
    # Prints the <allowed-ips> lines; empty output for an empty list.
    varname="$1"
    list="$2"
    out=""
    OLD_IFS="$IFS"
    IFS=','
    set -f
    # shellcheck disable=SC2086 # deliberate: split the list on the IFS above.
    set -- $list
    set +f
    IFS="$OLD_IFS"
    for cidr in "$@"; do
        cidr="$(printf '%s' "$cidr" | tr -d '[:space:]')"
        [ -n "$cidr" ] || continue
        case "$cidr" in
            0.0.0.0/0|::/0)
                _reject_cidr "$varname" "$cidr" \
                    "a default route would make the fence decorative" ;;
        esac
        # IPv4 a.b.c.d/len or IPv6 hex:colon/len. Anything else — every awk and
        # sed metacharacter included — is refused rather than interpolated.
        if ! printf '%s' "$cidr" | grep -Eq '^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$|^[0-9A-Fa-f:]+/[0-9]{1,3}$'; then
            _reject_cidr "$varname" "$cidr" \
                "not a CIDR (expected a.b.c.d/len or an IPv6 prefix/len)"
        fi
        out="${out}    <allowed-ips>${cidr}</allowed-ips>
"
    done
    printf '%s' "$out"
}

AGENT_EXTRA="$(_build_allowed_ips WAZUH_ALLOWED_IPS "${WAZUH_ALLOWED_IPS:-}")"
SYSLOG_EXTRA="$(_build_allowed_ips WAZUH_SYSLOG_ALLOWED_IPS "${WAZUH_SYSLOG_ALLOWED_IPS:-}")"

if [ -n "$AGENT_EXTRA" ] || [ -n "$SYSLOG_EXTRA" ]; then
    # awk, not `sed …/g`: the fences have to be widened PER BLOCK. The syslog
    # <remote> is identified by its own <connection>syslog</connection> line,
    # which precedes its <allowed-ips>; everything else (the `secure` <remote>
    # and <auth>) is the authenticated side.
    awk -v agent="$AGENT_EXTRA" -v syslog="$SYSLOG_EXTRA" '
        { print }
        /<connection>syslog<\/connection>/ { in_syslog = 1 }
        /<allowed-ips>127\.0\.0\.1\/32<\/allowed-ips>/ {
            if (in_syslog) printf "%s", syslog; else printf "%s", agent
        }
        /<\/remote>/ { in_syslog = 0 }
    ' "$MGR_DIR/ossec.conf" > "$MGR_DIR/ossec.conf.new"
    mv "$MGR_DIR/ossec.conf.new" "$MGR_DIR/ossec.conf"
    [ -z "$AGENT_EXTRA" ] || \
        echo "[wazuh-securityconfig-init] widened the AGENT fences with: ${WAZUH_ALLOWED_IPS:-}"
    [ -z "$SYSLOG_EXTRA" ] || \
        echo "[wazuh-securityconfig-init] widened the UNAUTHENTICATED syslog fence with: ${WAZUH_SYSLOG_ALLOWED_IPS:-}"
fi

# ── SIEM mail (#2002) — on whenever a recipient exists ────────────────────────
# A SIEM that only writes to its own dashboard requires someone to go and look.
# The recipient is RAZZFAZZ_OPERATOR_EMAIL (seeded by init), else
# ADMIN_CONTACT_EMAIL; with neither, alert mail stays OFF and this log says so —
# silence here would be the defect this block exists to remove. Inputs are
# validated and rejected the same way the CIDRs above are: they land in XML.
_mail_to="${RAZZFAZZ_OPERATOR_EMAIL:-${ADMIN_CONTACT_EMAIL:-}}"
_mail_from="${SMTP_FROM:-}"
_mail_level="${WAZUH_EMAIL_ALERT_LEVEL:-12}"
if [ -n "$_mail_to" ]; then
    printf '%s' "$_mail_to" | grep -Eq '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z0-9-]+$' \
        || _reject_cidr RAZZFAZZ_OPERATOR_EMAIL "$_mail_to" "not an e-mail address (one mailbox, no display name, no list)"
    printf '%s' "$_mail_from" | grep -Eq '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z0-9-]+$' \
        || _reject_cidr SMTP_FROM "$_mail_from" "not an e-mail address - the relay needs a sender"
    printf '%s' "$_mail_level" | grep -Eq '^([0-9]|1[0-6])$' \
        || _reject_cidr WAZUH_EMAIL_ALERT_LEVEL "$_mail_level" "not a Wazuh alert level (0-16)"
    # Both anchors are lines of the tracked ossec.conf; a rewrite that loses
    # either must fail here, not ship a manager that silently does not mail.
    grep -q '<email_notification>no</email_notification>' "$MGR_DIR/ossec.conf" \
        || _reject_cidr ossec.conf "<email_notification>" "anchor line missing - the tracked ossec.conf changed shape"
    grep -q '<log_alert_level>' "$MGR_DIR/ossec.conf" \
        || _reject_cidr ossec.conf "<log_alert_level>" "anchor line missing - the tracked ossec.conf changed shape"
    awk -v to="$_mail_to" -v from="$_mail_from" -v lvl="$_mail_level" '
        /<email_notification>no<\/email_notification>/ {
            print "    <email_notification>yes</email_notification>"
            print "    <smtp_server>smtp-relay</smtp_server>"
            print "    <email_from>" from "</email_from>"
            print "    <email_to>" to "</email_to>"
            next
        }
        { print }
        /<log_alert_level>/ { print "    <email_alert_level>" lvl "</email_alert_level>" }
    ' "$MGR_DIR/ossec.conf" > "$MGR_DIR/ossec.conf.new"
    mv "$MGR_DIR/ossec.conf.new" "$MGR_DIR/ossec.conf"
    echo "[wazuh-securityconfig-init] alert mail ON: level>=${_mail_level} -> ${_mail_to} via smtp-relay (from ${_mail_from})"
else
    echo "[wazuh-securityconfig-init] alert mail OFF: no recipient - set RAZZFAZZ_OPERATOR_EMAIL (or ADMIN_CONTACT_EMAIL) in .env and re-run post-install (#2002)"
fi

# ── Cloud: aws-s3 wodle (#1874 part 4) — activate-on-creds ────────────────────
# When WAZUH_AWS_S3_BUCKET is set, inject a <wodle name="aws-s3"> before
# </ossec_config>. Credentials come from the standard AWS chain via <aws_profile>
# (inline access/secret keys were DEPRECATED in Wazuh 4.4) — NO secret enters this
# file. Inputs are validated + rejected the same way the CIDRs above are.
if [ -n "${WAZUH_AWS_S3_BUCKET:-}" ]; then
    _bkt="$WAZUH_AWS_S3_BUCKET"
    printf '%s' "$_bkt" | grep -Eq '^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$' \
        || _reject_cidr WAZUH_AWS_S3_BUCKET "$_bkt" "not a valid S3 bucket name (3-63, lowercase a-z 0-9 . -)"
    _ltype="${WAZUH_AWS_S3_LOG_TYPE:-cloudtrail}"
    printf '%s' "$_ltype" | grep -Eq '^[a-z_]+$' \
        || _reject_cidr WAZUH_AWS_S3_LOG_TYPE "$_ltype" "not a valid bucket type (lowercase letters/underscore)"
    _region_line=""; _profile_line=""
    if [ -n "${WAZUH_AWS_REGION:-}" ]; then
        printf '%s' "$WAZUH_AWS_REGION" | grep -Eq '^[a-z]{2}-[a-z]+-[0-9]$' \
            || _reject_cidr WAZUH_AWS_REGION "$WAZUH_AWS_REGION" "not an AWS region (e.g. eu-central-1)"
        _region_line="      <regions>${WAZUH_AWS_REGION}</regions>
"
    fi
    if [ -n "${WAZUH_AWS_PROFILE:-}" ]; then
        printf '%s' "$WAZUH_AWS_PROFILE" | grep -Eq '^[A-Za-z0-9_.-]+$' \
            || _reject_cidr WAZUH_AWS_PROFILE "$WAZUH_AWS_PROFILE" "not a valid AWS profile name"
        _profile_line="      <aws_profile>${WAZUH_AWS_PROFILE}</aws_profile>
"
    fi
    _aws_wodle="  <wodle name=\"aws-s3\">
    <disabled>no</disabled>
    <interval>10m</interval>
    <run_on_start>yes</run_on_start>
    <bucket type=\"${_ltype}\">
      <name>${_bkt}</name>
${_region_line}${_profile_line}    </bucket>
  </wodle>
"
    if grep -q '<wodle name="aws-s3">' "$MGR_DIR/ossec.conf"; then
        echo "[wazuh-securityconfig-init] aws-s3 wodle already present — leaving it"
    else
        awk -v w="$_aws_wodle" '/<\/ossec_config>/ && !ins { printf "%s", w; ins=1 } { print }' \
            "$MGR_DIR/ossec.conf" > "$MGR_DIR/ossec.conf.new"
        mv "$MGR_DIR/ossec.conf.new" "$MGR_DIR/ossec.conf"
        echo "[wazuh-securityconfig-init] injected aws-s3 wodle: bucket=${_bkt} type=${_ltype}"
    fi
fi

printf '%s' "$WAZUH_AUTHD_PASSWORD" > "$MGR_DIR/authd.pass"
chmod 0640 "$MGR_DIR/authd.pass"
chmod 0644 "$MGR_DIR/ossec.conf"

echo "[wazuh-securityconfig-init] wrote internal_users.yml, config.yml, roles_mapping.yml, ossec.conf, authd.pass"
