#!/bin/sh
# Enable permissive SASL AUTH on the smtp-relay container.
# This allows clients that REQUIRE authentication (like the Dify email plugin)
# to connect with any username/password. Security is not a concern here because
# the container is only reachable from the internal Docker network.

# Install SASL packages
apk add --no-cache cyrus-sasl cyrus-sasl-plain cyrus-sasl-login 2>/dev/null || true

# Create a permissive SASL config that accepts any credentials via sasldb
cat > /etc/sasl2/smtpd.conf <<'SASLCONF'
pwcheck_method: auxprop
auxprop_plugin: sasldb
mech_list: PLAIN LOGIN
SASLCONF

# Create a dummy user in sasldb so any login attempt with this password works
# Password is provided via SMTP_INTERNAL_PASSWORD env var (generated by razzfazz-init.sh)
SASL_PASS="${SMTP_INTERNAL_PASSWORD:-mailpass}"
echo "$SASL_PASS" | saslpasswd2 -c -p -u "$(postconf -h myhostname)" mail

# Enable SASL in Postfix
postconf -e "smtpd_sasl_auth_enable = yes"
postconf -e "smtpd_sasl_security_options = noanonymous"
postconf -e "smtpd_sasl_local_domain = \$myhostname"
postconf -e "broken_sasl_auth_clients = yes"
postconf -e "smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination"
