#!/usr/bin/env bash
set -euo pipefail
# modules/apps/wazuh/configs/wazuh_dashboard/render-dashboard-config.sh — #855
#
# Runs as the wazuh-dashboard-config-init one-shot inside the pinned
# wazuh-dashboard image, before the dashboard starts. It renders
# opensearch_dashboards.yml because that file must carry the OIDC CLIENT
# SECRET, so it cannot be a tracked, bind-mounted file.
#
# The config dir is a named volume that Docker pre-populated from this same
# image, so node.options and every other shipped file are still the image's.

CONF=/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
: "${WAZUH_AUTH_MODE:?WAZUH_AUTH_MODE is empty - expected native_oidc or forward_auth}"

cat > "$CONF" <<'EOF'
# GENERATED by render-dashboard-config.sh (#855). Do not edit: the
# wazuh-dashboard-config-init one-shot overwrites it on every `up`.
server.host: 0.0.0.0
server.port: 5601
# Caddy terminates TLS at wazuh.<domain>; this listener is loopback-published
# and reached over the docker bridge, so it speaks plaintext.
server.ssl.enabled: false
# #1259: the indexer's SAN is `wazuh.indexer` (a network alias on the
# wazuh-indexer service) — the cert tool refuses a dotless SAN, so the
# hyphenated service name is on no certificate. verificationMode `certificate`
# would tolerate either, but there is exactly one right name and this is it.
opensearch.hosts: https://wazuh.indexer:9200
opensearch.ssl.verificationMode: certificate
opensearch.ssl.certificateAuthorities: ["/usr/share/wazuh-dashboard/certs/root-ca.pem"]
opensearch.requestHeadersWhitelist: ["securitytenant", "Authorization"]
opensearch_security.multitenancy.enabled: false
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
uiSettings.overrides.defaultRoute: /app/wz-home
opensearch_security.cookie.secure: true
opensearch_security.cookie.ttl: 900000
opensearch_security.session.ttl: 900000
opensearch_security.session.keepalive: true
EOF

if [ "$WAZUH_AUTH_MODE" = "native_oidc" ]; then
    : "${WAZUH_OIDC_CLIENT_ID:?WAZUH_OIDC_CLIENT_ID is empty}"
    : "${WAZUH_OIDC_CLIENT_SECRET:?WAZUH_OIDC_CLIENT_SECRET is empty - run rzfz init or rzfz upgrade}"
    : "${WAZUH_DOMAIN:?WAZUH_DOMAIN is empty}"
    : "${AUTHENTIK_DOMAIN:?AUTHENTIK_DOMAIN is empty}"
    # UNQUOTED heredoc — the ${…} below must expand. The price is that a
    # backtick inside it is COMMAND SUBSTITUTION, prose or not: pre-rev-C the
    # comments here ran `groups` and five other "commands" on every render and
    # wrote the results into the emitted YAML comments. Every backtick in this
    # block therefore stays backslash-escaped. Guarded by
    # tests/unit/consistency/test_855_wazuh_render_heredocs.py.
    cat >> "$CONF" <<EOF

# ── Authentik OIDC (blueprint core/Authentik/blueprints/base/37-wazuh.yaml) ──
# The security plugin serves the callback at <base_redirect_url>/auth/openid/login,
# which is exactly the redirect_uri the blueprint registers.
opensearch_security.auth.type: "openid"
# The discovery path is the Authentik APPLICATION SLUG, never the client_id
# (rev-B LOW 18 + blocker 4). Since blocker 4 split the app in two — proxy app
# \`wazuh\` for the forward-auth gate, hidden \`wazuh-oidc\` for this provider —
# the slug that serves /application/o/<slug>/ for the OAuth2 provider is
# \`wazuh-oidc\`. Same shape as modules/gitea/init-gitea.sh:101. Substituting
# ${WAZUH_OIDC_CLIENT_ID} here silently 404s the moment an operator changes
# the client id.
opensearch_security.openid.connect_url: "https://${AUTHENTIK_DOMAIN}/application/o/wazuh-oidc/.well-known/openid-configuration"
opensearch_security.openid.client_id: "${WAZUH_OIDC_CLIENT_ID}"
opensearch_security.openid.client_secret: "${WAZUH_OIDC_CLIENT_SECRET}"
opensearch_security.openid.base_redirect_url: "https://${WAZUH_DOMAIN}"
# \`groups\` is NOT optional (rev-B HIGH 6). Authentik emits a claim only for a
# REQUESTED scope — 06-oauth-groups-scope.yaml declares scope_name \`groups\`,
# and every other consumer asks for it by name (Gitea \`--scopes "groups"\`,
# Open WebUI \`openid email profile groups\`). Without it the id_token carries no
# \`groups\`, the indexer's \`roles_key: groups\` resolves to zero backend roles,
# and EVERY SSO user — Super Admins included — lands role-less with an empty
# dashboard or a 403. That is exactly the outcome the LOAD-BEARING comment on
# the groups scopemapping in 37-wazuh.yaml warns about; attaching the mapping
# to the provider is only half of it, the client has to ask.
opensearch_security.openid.scope: "openid profile email groups"
opensearch_security.openid.logout_url: "https://${AUTHENTIK_DOMAIN}/application/o/wazuh-oidc/end-session/"
opensearch_security.openid.verify_hostnames: true
# On a TLS_MODE=internal box Authentik is served by Caddy with the box's own
# CA; cli/init.sh (#55 Step 7a) writes it to <repo>/certs/caddy-ca.pem, which
# the compose file binds in read-only.
opensearch_security.openid.root_ca: "/usr/local/share/ca-certificates/caddy-ca.crt"
EOF
else
    cat >> "$CONF" <<'EOF'

# WAZUH_AUTH_MODE=forward_auth — Caddy's Authentik gate is the only
# authenticator; the dashboard uses local basic auth (DECISION-5 fallback).
opensearch_security.auth.type: "basicauth"
EOF
fi

# ── #855 / OIDC diagnosis: an OFF-BY-DEFAULT maintainer's tool ───────────────
#
# The runtime opensearch_dashboards.yml is immutable on a running box — an
# in-container write is refused even as root, and the host file is not writable
# via sudo either. Measured on 0.91. THIS script is the only writer, so a
# diagnostic that has to reach that file has to be rendered here.
#
# Why it is needed: an SSO user can log in through Authentik and still land
# role-less. Three causes look identical from outside — the claim is not
# emitted, the claim carries a different name than the rolesmapping expects, or
# the dashboard does not turn the backend role into an authorization. Only the
# token the dashboard actually received tells them apart, and the only way to
# see it is the security plugin's own debug log.
#
# Off unless WAZUH_DASHBOARD_DEBUG_SECURITY is exactly "true": a debug logger on
# this plugin writes decoded token contents into the container log, which is a
# disclosure a box must not carry by accident. `1`, `yes` and `TRUE` do NOT turn
# it on — a diagnostic that switches itself on for a value someone typed by
# habit is the wrong kind of forgiving.
if [ "${WAZUH_DASHBOARD_DEBUG_SECURITY:-false}" = "true" ]; then
    cat >> "$CONF" <<'EOF'

# TEMPORARY DIAGNOSTIC — rendered only because
# WAZUH_DASHBOARD_DEBUG_SECURITY=true. It logs the security plugin's view of
# each login, INCLUDING decoded token contents. Unset the variable and re-run
# the config-init one-shot to remove it again.
logging.loggers:
  - name: plugins.securityDashboards
    level: debug
    appenders: [default]
EOF
    echo "[wazuh-dashboard-config-init] SECURITY DEBUG LOGGING IS ON — token contents will appear in this container's log. Unset WAZUH_DASHBOARD_DEBUG_SECURITY when done."
fi

echo "[wazuh-dashboard-config-init] wrote $CONF (auth mode: $WAZUH_AUTH_MODE)"
