#!/usr/bin/env bash
# SPDX-License-Identifier: BUSL-1.1
# Copyright © 2024–2026 razzfazz.ai GmbH – Member of SEQIS Group.
# =============================================================================
# generate-source-mirror.sh — build the Corresponding-Source mirror (#68)
# =============================================================================
# For every BUNDLED / BUILT copyleft upstream (AGPL-3.0 / GPL-3.0 / LGPL-3.0)
# that we redistribute, GPL/AGPL §6 requires us to provide the *Corresponding
# Source* at the EXACT version we ship. A bare "link to the upstream tag" is
# permitted (GPLv3 §6(d)) but we are then on the hook for that link's continued
# availability — fragile. This script produces a durable, version-pinned SOURCE
# MIRROR (a `git bundle` per component at its exact pinned tag) that a release
# publishes as an asset ALONGSIDE the Codeberg snapshot. THIRD-PARTY-NOTICES.md
# points at `source-mirror/<comp>-<version>.bundle` (release asset) with the
# upstream tag as a secondary reference.
#
# This is a RELEASE step (like scripts/publish-public.sh) — it clones several GB
# of upstream history and is NOT run on every build. It writes into
# `source-mirror/` at the repo root (git-ignored; published as release assets).
#
# Usage:
#   scripts/generate-source-mirror.sh              # build all bundles
#   scripts/generate-source-mirror.sh --list       # print the component matrix
#   scripts/generate-source-mirror.sh vaultwarden  # just one component
#
# The version tags below are the SINGLE list to keep in step with the pinned
# image versions (mirror of scripts/generate-notice.py ENRICH). A release
# pre-flight should assert they match the compose image: pins / versions.json.
# =============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${REPO_ROOT}/source-mirror"

# component | repo | tag | SPDX
COMPONENTS=(
  "vaultwarden|https://github.com/dani-garcia/vaultwarden|1.36.0|AGPL-3.0"
  "searxng|https://github.com/searxng/searxng|2026.6.13-a29cda858|AGPL-3.0"
  "synapse|https://github.com/element-hq/synapse|v1.154.0|AGPL-3.0"
  "element-web|https://github.com/element-hq/element-web|v1.12.21|AGPL-3.0"
  "komodo|https://github.com/moghtech/komodo|v2.2.0|GPL-3.0"
  "paperless-ngx|https://github.com/paperless-ngx/paperless-ngx|v2.20.15|GPL-3.0"
  # LGPL library we bundle (dynamically linked, unmodified) — include for
  # completeness; comment out if not required by counsel.
  "psycopg2|https://github.com/psycopg/psycopg2|2_9_10|LGPL-3.0"
)

say() { echo "[source-mirror] $*"; }

if [ "${1:-}" = "--list" ]; then
  printf '%-16s %-12s %-45s %s\n' "COMPONENT" "SPDX" "REPO" "TAG"
  for row in "${COMPONENTS[@]}"; do
    IFS='|' read -r name repo tag spdx <<<"$row"
    printf '%-16s %-12s %-45s %s\n' "$name" "$spdx" "$repo" "$tag"
  done
  exit 0
fi

ONLY="${1:-}"
mkdir -p "$OUT"

build_one() {
  local name="$1" repo="$2" tag="$3" spdx="$4"
  local bundle="${OUT}/${name}-${tag}.bundle"
  if [ -f "$bundle" ]; then say "exists, skipping: $(basename "$bundle")"; return 0; fi
  local tmp; tmp="$(mktemp -d)"
  say "cloning ${name} @ ${tag} (${spdx}) …"
  if ! git clone --quiet --bare --depth 1 --branch "$tag" "$repo" "$tmp/repo.git"; then
    say "WARN: tag '$tag' not directly clonable for ${name}; trying full clone + checkout"
    rm -rf "$tmp/repo.git"
    git clone --quiet --bare "$repo" "$tmp/repo.git"
  fi
  # Bundle the exact ref so the mirror is self-contained + verifiable offline.
  ( cd "$tmp/repo.git" && git bundle create "$bundle" --all )
  rm -rf "$tmp"
  say "wrote $(basename "$bundle") ($(du -h "$bundle" | cut -f1))"
}

# Provenance manifest for the release/audit trail.
manifest="${OUT}/SOURCE-MIRROR.md"
{
  echo "# Corresponding Source mirror"
  echo
  echo "Generated by scripts/generate-source-mirror.sh. Each bundle is the exact"
  echo "upstream source of a redistributed copyleft image, at the version we ship."
  echo "Published as release assets; referenced from THIRD-PARTY-NOTICES.md."
  echo
  echo "| Component | SPDX | Tag | Bundle | Upstream |"
  echo "|---|---|---|---|---|"
} > "$manifest"

for row in "${COMPONENTS[@]}"; do
  IFS='|' read -r name repo tag spdx <<<"$row"
  [ -n "$ONLY" ] && [ "$ONLY" != "$name" ] && continue
  build_one "$name" "$repo" "$tag" "$spdx"
  echo "| $name | $spdx | $tag | \`source-mirror/${name}-${tag}.bundle\` | ${repo}/tree/${tag} |" >> "$manifest"
done

say "done. Mirror in ${OUT} (publish as release assets)."
say "manifest: ${manifest}"
